export const LOAD_QUESTION_REQUEST = "LOAD_QUESTION_REQUEST";
export const LOAD_QUESTION_SUCCESS = "LOAD_QUESTION_SUCCESS";
export const LOAD_QUESTION_FAILURE = "LOAD_QUESTION_FAILURE";

export const LOAD_ANSWER_REQUEST = "LOAD_ANSWER_REQUEST";
export const LOAD_ANSWER_SUCCESS = "LOAD_ANSWER_SUCCESS";
export const LOAD_ANSWER_FAILURE = "LOAD_ANSWER_FAILURE";

export const KEY_WORD_SEARCH_REQUEST = "KEY_WORD_SEARCH_REQUEST";
export const KEY_WORD_SEARCH_SUCCESS = "KEY_WORD_SEARCH_SUCCESS";
export const KEY_WORD_SEARCH_FAILURE = "KEY_WORD_SEARCH_FAILURE";

export const WRITE_QUESTION_REQUEST = "WRITE_QUESTION_REQUEST";
export const WRITE_QUESTION_SUCCESS = "WRITE_QUESTION_SUCCESS";
export const WRITE_QUESTION_FAILURE = "WRITE_QUESTION_FAILURE";

export const WRITE_ANSWER_REQUEST = "WRITE_ANSWER_REQUEST";
export const WRITE_ANSWER_SUCCESS = "WRITE_ANSWER_SUCCESS";
export const WRITE_ANSWER_FAILURE = "WRITE_ANSWER_FAILURE";

export const UNLIKE_QUESTION_REQUEST = "UNLIKE_QUESTION_REQUEST";
export const UNLIKE_QUESTION_SUCCESS = "UNLIKE_QUESTION_SUCCESS";
export const UNLIKE_QUESTION_FAILURE = "UNLIKE_QUESTION_FAILURE";

export const LIKE_QUESTION_REQUEST = "LIKE_QUESTION_REQUEST";
export const LIKE_QUESTION_SUCCESS = "LIKE_QUESTION_SUCCESS";
export const LIKE_QUESTION_FAILURE = "LIKE_QUESTION_FAILURE";

export const UNLIKE_ANSWER_REQUEST = "UNLIKE_ANSWER_REQUEST";
export const UNLIKE_ANSWER_SUCCESS = "UNLIKE_ANSWER_SUCCESS";
export const UNLIKE_ANSWER_FAILURE = "UNLIKE_ANSWER_FAILURE";

export const LIKE_ANSWER_REQUEST = "LIKE_ANSWER_REQUEST";
export const LIKE_ANSWER_SUCCESS = "LIKE_ANSWER_SUCCESS";
export const LIKE_ANSWER_FAILURE = "LIKE_ANSWER_FAILURE";

export const DETAIL_QUESTION_REQUEST = "DETAIL_QUESTION_REQUEST";
export const DETAIL_QUESTION_SUCCESS = "DETAIL_QUESTION_SUCCESS";
export const DETAIL_QUESTION_FAILURE = "DETAIL_QUESTION_FAILURE";

export const BOOKMARK_REQUEST = "BOOKMARK_REQUEST";
export const BOOKMARK_SUCCESS = "BOOKMARK_SUCCESS";
export const BOOKMARK_FAILURE = "BOOKMARK_FAILURE";

export const DELETE_BOOKMARK_REQUEST = "DELETE_BOOKMARK_REQUEST";
export const DELETE_BOOKMARK_SUCCESS = "DELETE_BOOKMARK_SUCCESS";
export const DELETE_BOOKMARK_FAILURE = "DELETE_BOOKMARK_FAILURE";
