export const LOG_IN_REQUEST = "LOG_IN_REQUEST";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAILURE = "LOG_IN_FAILURE";

export const REQUEST_PROVIDER_REQUEST = "REQUEST_PROVIDER_REQUEST";
export const REQUEST_PROVIDER_SUCCESS = "REQUEST_PROVIDER_SUCCESS";
export const REQUEST_PROVIDER_FAILURE = "REQUEST_PROVIDER_FAILURE";

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const CHECK_NICKNAME_REQUEST = "CHECK_NICKNAME_REQUEST";
export const CHECK_NICKNAME_SUCCESS = "CHECK_NICKNAME_SUCCESS";
export const CHECK_NICKNAME_FAILURE = "CHECK_NICKNAME_FAILURE";
